start run_race_tri_rl_rn_all_maxlogit.bat
start run_race_tri_rl_rn_all_tied_aggre_tied_match_rn_soft_sumlogit.bat
start run_race_tri_rl_rn_all_drop0.5_sumlogit.bat
start run_race_tri_rl_rn_all_morelayers_drop0.5_sumlogit.bat
