start run_race_tri_rl_rn_middle_nontie_aggre_nontie_match_rn_soft_sumlogit.bat
start run_race_tri_rl_rn_middle_tied_aggre_tied_match_rn_soft_sumlogit.bat
start run_race_tri_rl_rn_middle_nontie_aggre_nontie_match_rn_ori_keepfirst_sumlogit.bat
start run_race_tri_rl_rn_middle_tied_aggre_tied_match_rn_ori_keepfirst_sumlogit.bat
